name: multiple_dialog
description: This is a magazine with multiple material designs and easy use like showAboutDialog
version: 0.1.5
author: Lans <wylans@163.com>
homepage: https://github.com/Lans/multiple_dialog

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
